name: Ant PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  ant-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run ant-pr
        uses: qkitzero/ant-pr@v1.1.0
        with:
          base-sha: ${{ github.event.pull_request.base.sha }}
          head-sha: ${{ github.event.pull_request.head.sha }}
          config-path: ".github/workflows/.ant-pr.yml"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
